dnovel/urls.py
from adminplus.sites import AdminSitePlus
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
#from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from dnovel import settings


admin.site = AdminSitePlus()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^xmy/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'', include('novel.urls')),
    # url(r'^dnovel/', include('dnovel.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

novel/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static

__author__ = 'meng'

from django.conf.urls import patterns,url
from novel import views

urlpatterns = patterns('',
    url(r'^$',views.index,name='index'),
    url(r'^(?P<category_alias>[A-Za-z]+)/$',views.category,name='category'),
    url(r'^book/(?P<book_alias>[A-Za-z]+)/$',views.book,name='book'),
    url(r'^book/(?P<book_alias>[A-Za-z]+)/(?P<chapter_id>\d+)\.html$',views.chapter,name='chapter'),
    url(r'^book/(?P<book_alias>[A-Za-z]+)/download/$',views.book_download,name="novel_download"),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),

    url(r'^temp_test$',views.temp_text)
)

novel/models.py
#encoding:utf-8
from django.db import models,connection
# Create your models here.
from django.utils.encoding import python_2_unicode_compatible
from tinymce.models import HTMLField


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=50)
    alias = models.CharField(max_length=100,unique=True)

    @property
    def get_category_url(self):
        return '/%s/' % self.alias
    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Novel(models.Model):
    category = models.ForeignKey(Category)
    name = models.CharField(u"小说名",max_length=100,db_index=True)
    alias = models.CharField(u"小说拼音",max_length=100,unique=True,db_index=True,blank=True)
    author = models.CharField(u'作者',max_length=50,blank=True)
    description = models.TextField(u"小说简介",blank=True)
    last_chapter = models.IntegerField(u'最新章节',blank=True,default=0)
    is_over = models.BooleanField(u"小说是否完结",blank=True)
    image = models.ImageField(u"封面图片",upload_to='novel_cover',max_length=255,blank=True)
    hot = models.IntegerField(db_index=True,default=1)
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    start_url = models.CharField(u"采集起始URL",max_length=255,blank=True)
    spider_class = models.CharField(u"采集类",max_length=20,blank=True)
    interval = models.SmallIntegerField(u"采集间隔",blank=True)

    seo_title = models.CharField(u"SEO标题",max_length=255,blank=True)
    seo_keyword = models.CharField(u"SEO关键字",max_length=255,blank=True)
    seo_description = models.TextField(u"SEO描述",blank=True)

    #@property
    #def last_chapter(self):
    #    return self.chapter_set.order_by('-order')[0] or None
    #    #return self.chapter.

    @property
    def get_last_chapter(self):
        if self.last_chapter:
            try:
                chapter = Chapter.objects.filter(novel = self,order = self.last_chapter).get()
            except:
                chapter = self.chapter_set.order_by('-order')[0] or None
            return chapter
        else:
            return self.chapter_set.order_by('-order')[0] or None
    @property
    def get_novel_url(self):
        return '/book/%s/' % self.alias
    @property
    def get_novel_download_url(self):
        return '/book/%s/download/'% self.alias
    @property
    def get_novel_chapter(self):
        """"""
        volume = Chapter.objects.filter(novel = self).values("volume","volume_name").order_by("volume").distinct()
        chapterlist = self.chapter_set.all()
        result = dict()
        for v in volume:
            _r = []
            for chapter in chapterlist:
                if chapter.volume == v['volume']:
                    _r.append(chapter)
            result[v['volume_name']] = _r
        return result



    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-hot']
        index_together = [
            ['id','last_chapter']
        ]
@python_2_unicode_compatible
class Chapter(models.Model):
    novel = models.ForeignKey(Novel,db_index=True)
    name = models.CharField(r'章节名',max_length=255)
    content = HTMLField(u'内容')
    volume = models.SmallIntegerField(default=1)
    volume_name = models.CharField(max_length=50,default=u'正文')
    order = models.IntegerField(unique=True,db_index=True)
    update_time = models.DateTimeField(auto_now=True)

    @property
    def get_chapter_url(self):
        return '/book/%s/%s.html' %(self.novel.alias,self.order)
    @property
    def next_chapter(self):
        next = Chapter.objects.filter(novel=self.novel,order__gt = self.order).order_by('order')
        return next[0].get_chapter_url if next else None
    @property
    def prev_chapter(self):
        prev = Chapter.objects.filter(novel=self.novel,order__lt = self.order).latest('order')
        return prev.get_chapter_url if prev else None



    def __str__(self):
        return self.name
    class Meta:
        ordering = ['order']
        index_together = [
            ['novel','order']
        ]


@python_2_unicode_compatible
class SEO(models.Model):
    index_book = models.OneToOneField(Novel)
    index_seo_title = models.CharField(u'网站首页SEO标题',max_length=100,blank=True)
    index_seo_keywords = models.CharField("首页seo关键字",max_length=255,blank=True)
    index_seo_description = models.CharField("首页seo描述",max_length=255,blank=True)
    site_name = models.CharField(u'网站名',max_length=50,blank=True)
    site_sub_name = models.CharField(u'网站副标题',max_length=100,blank=True)
    site_url = models.CharField("网站地址",blank=True,max_length=50,default='/')
    tongji = models.TextField(u'统计代码',blank=True)
    google = models.CharField(u'google统计ID',max_length=20,blank=True)

    def __str__(self):
        return self.index_book.name

@python_2_unicode_compatible
class Links(models.Model):
    name = models.CharField(u'网站名',max_length=50)
    url = models.CharField(u'网站URL',max_length=100)
    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Collection(models.Model):
    novel = models.ForeignKey(Novel)
    book = models.CharField(max_length=40)
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=255)
    url_hash = models.CharField(max_length=40,db_index=True)

    def __str__(self):
        self.name

templates/temp1/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <meta name="keywords" content="{% block keywords %}{% endblock %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="viewport" content="width=device-width">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-theme.min.css" %}">
    <link rel="stylesheet" href="{% static "main.css" %}"/>
    <script src="{% static "js/modernizr-2.6.2-respond-1.1.0.min.js" %}"></script>
</head>
{% block body %}
<body>
{% block line %}
    <div class="redBorder"></div>
    <div class="greenBorder"></div>
    <div class="yellowBorder"></div>
{% endblock %}
    {% block header %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block other %}
    {% endblock %}
{% block footer %}
    <footer>
        <div class="container" style="color: #d6d6d6">
            {% block youlian %}

            {% endblock %}
            <div class="banquan">
                <p class="text-center">本站所有小说为转载作品，所有章节均由网友上传，转载至本站只是为了宣传本书让更多读者欣赏。</p>
                <p class="text-center">Copyright © 2013 {{ site_name }} All Rights Reserved.{{ tongji|safe }}</p>
            </div>
        </div>
    </footer>
{% endblock %}

    <script src="//cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static "js/jquery-1.10.1.min.js" %}"><\/script>')</script>
{#    <script src="{% static "js/bootstrap.min.js" %}"></script>#}
    <script>var _gaq = [['_setAccount', '{{ google }}'],['_trackPageview']];(function (d, t) {var g = d.createElement(t), s = d.getElementsByTagName(t)[0];g.src = '//www.google-analytics.com/ga.js';s.parentNode.insertBefore(g, s)}(document, 'script'));</script>
</body>
{% endblock %}

</html>

templates/temp1/book.html
{% extends "base.html" %}
{% block title %}{{ novel.seo_title }}{% endblock %}
{% block description %}{{ novel.seo_description }}{% endblock %}

{% block body %}
    <body style="background:#282b36 repeat-x scroll 0 0">
    {% block line %}
        {{ block.super }}
    {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <h2 style="color: #D6D6D6">
                <p class="book-category">
                    <a href="/">首页</a>
                    {% for category in category_list %}
                        {% if category_alias %}
                            {% ifequal category_alias category.alias %}
                                <a href="{{ category.get_category_url }}" class="active">{{ category }}</a>
                            {% else %}
                                <a href="{{ category.get_category_url }}">{{ category }}</a>
                            {% endifequal %}
                        {% elif novel.category %}
                            {% ifequal novel.category.alias category.alias %}
                                <a href="{{ category.get_category_url }}" class="active">{{ category }}</a>
                            {% else %}
                                <a href="{{ category.get_category_url }}">{{ category }}</a>
                            {% endifequal %}

                        {% endif %}
                    {% endfor %}
                </p>
            </h2>

        </div>
        <div class="row book-info">
            <a href="{{ novel.get_novel_url }}" title="{{ novel }}"><img src="{{ MEDIA_URL }}{{ novel.image }}"
                                                                         class="col-md-3" alt=""/></a>
            <div class="col-md-6">
                <div class="book-info-title">
                    <h2>
                        <a href="{{ novel.get_novel_url }}" title="{{ novel.name }}"   style="text-decoration:none;">{{ novel.name }}</a><small>{{ novel.author }}</small></h2>
                </div>
                <p>类型:{{ novel.category }}</p>
                <p>最新章节: <a href="{{ novel.last_chapter.get_chapter_url }}">{{ novel.last_chapter }}</a></p>
                <p>最近更新:{{ novel.last_chapter.update_time|date:'Y-m-d H:i' }} </p>
                <p style="height: 120px;overflow: hidden">简介:{{ novel.last_chapter.description|safe }}</p>
            </div>
            <div class="col-md-3">

            </div>
        </div>
        <div class="row book-chapter">
            <ul class="list-unstyled" style="width: 850px;margin: 0 auto;">
                {% for c in chapter_list %}
                    <li class="col-md-4 chapter limit-word" style="margin-bottom: 10px;"><a href="{{ c.get_chapter_url }}" title="{{ c.name }}">{{ c.name }}</a></li>
                {% endfor %}
            </ul>
        </div>

    </div>
{% endblock %}
    {% block footer %}
        {{ block.super }}
    {% endblock %}
    </body>
{% endblock %}

templates/temp1/category.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block description %}{{ index_seo_description }}{% endblock %}
{% block keywords %}{{ index_seo_keyword }}{% endblock %}

{% block body %}
    <body style="background:#282b36 repeat-x scroll 0 0">
    {% block line %}
        {{ block.super }}
    {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <h2 style="color: #333333">
                <p class="book-category">
                    <a href="/">首页</a>
                    {% for category in category_list %}
                        {% if category_alias %}
                            {% ifequal category_alias category.alias %}
                                <a href="{{ category.get_category_url }}" class="active">{{ category }}</a>
                            {% else %}
                                <a href="{{ category.get_category_url }}">{{ category }}</a>
                            {% endifequal %}
                        {% elif novel.category %}
                            {% ifequal novel.category.alias category.alias %}
                                <a href="{{ category.get_category_url }}" class="active">{{ category }}</a>
                            {% else %}
                                <a href="{{ category.get_category_url }}">{{ category }}</a>
                            {% endifequal %}

                        {% endif %}
                    {% endfor %}
                </p>
            </h2>

        </div>
        <div class="row novel-list">
            {% for novel in novel_list %}
                <div class="col-md-6 novel">
                    <div class="row">
                        <a href="{{ novel.get_novel_url }}" title="{{ novel }}"><img src="{{ MEDIA_URL }}{{ novel.image }}" alt="" class="col-md-4 col-xs-4" style="padding: 5px"/></a>
                        <div class="col-md-8 col-xs-8">
                            <p style="font-size: 24px;"><a href="{{ novel.get_novel_url }}" title="{{ novel }}">{{ novel.name }}</a></p>
                            <p>作 者:{{ novel.author }}</p>
                            <p>最新更新: <a href="{{ novel.last_chapter.get_chapter_url }}">{{ novel.last_chapter }}</a></p>
                            <p style="height: 100px">简介:{{ novel.description|safe }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

    {% block footer %}
        {{ block.super }}
    {% endblock %}
    </body>
{% endblock %}

templates/temp1/chapter.html
{% extends "base.html" %}
{% block title %}{% if book.seo_title %}{{ book.seo_title }}{% else %}{{ book.name }} 最新章节 无弹窗广告 {{ book.name }}TXT全文下载 -{{ site_name }}{% endif %}{% endblock %}
{% block keywords %}{% if book.seo_keyword %}{{ book.seo_keyword }}{% else %}{{ book.name }},{{ book.name }}无弹窗阅读,{{ book.name }}TXT全文下载,{{ book.name }}在线阅读{% endif %}{% endblock %}
{% block description %}{{ book.description }}{% endblock %}

{% block body %}
    <body style="background:#282b36 repeat-x scroll 0 0">
    {% block line %}
        {{ block.super }}
    {% endblock %}
    {% block content %}
        <div class="container" style="width: 1070px">
            <div class="row" style="background-color: #f1f1f1;margin-top: 20px;padding: 5px 5px 5px 5px;">
                <ul id="breadcrumbs-three" class="list-unstyled" style="margin-bottom: 0;">
                    <li>
                        <a href="/"><span class="glyphicon glyphicon-home"></span></a>
                    </li>
                    <li><a href="{{ book.category.get_category_url }}">{{ book.category.name }}</a></li>
                    <li><a href="{{ book.get_novel_url }}">{{ book.name }}</a></li>
                    <li><a href="#">{{ chapter.name }} 正文</a></li>
                </ul>
            </div>
            <div class="row" style="background-color: #f1f1f1;margin-top: 1px;margin-bottom: 20px;">
                <h2 class="text-center">{{ chapter.name }}</h2>
                <script language=javascript>
                    document.onkeydown=nextpage
                    var prevpage="{{ chapter.prev_chapter }}" //向左
                    var nextpage="{{ chapter.next_chapter }}" //向右
                    var bookpage="{{ book.get_novel_url }}" //回车
                    function nextpage(event)
                    {
                     event = event ? event : (window.event ? window.event : null);

                     if (event.keyCode==13) location=bookpage;//回车
                     if (event.keyCode==37) location=prevpage;//向左
                     if (event.keyCode==39) location=nextpage;//向右

                    }

                    </script>
                <p class="text-center">
                    <a href="{{ chapter.prev_chapter }}">上一章</a>
                    <a href="{{ book.get_novel_url }}" STYLE="margin-left: 5px;margin-right: 5px">返回目录</a>
                    <a href="{{ chapter.next_chapter }}">下一章</a>
                </p>
                <hr style="border-top: 1px dotted #333333;margin-top: 5px"/>
                {{ chapter_top_ads }}
                <div class="chapter-content">
                    {{ chapter.content|safe }}
                    <p class="text-center">
                        <a href="{{ chapter.prev_chapter }}">上一章</a>
                        <a href="{{ book.get_novel_url }}" STYLE="margin-left: 5px;margin-right: 5px">返回目录</a>
                        <a href="{{ chapter.next_chapter }}">下一章</a>
                    </p>
                </div>
                {{ chapter_bottm_ads }}
            </div>

        </div>
    {% endblock %}
    {% block footer %}
        {{ block.super }}
    {% endblock %}
    </body>
{% endblock %}

templates/temp1/index.html
{% extends "base.html" %}
{% block title %}{{ seo.index_seo_title }}-{{ site_name }}{% endblock %}
{% block description %}{{ index_book.seo_description|safe }}{% endblock %}
{% block header %}
    <header class="text-center container">
        <h1>
            <span class="glyphicon glyphicon-book"></span> {{ site_name }}
        </h1>

        <h3 class="site-name">
            {{ site_subname }}
        </h3>
    </header>
{% endblock %}
{% block content %}
<div class="container">
    <div class="category">
        <h3 class="category-hot">热门推荐</h3>
        <ul class="list-unstyled">
            {% for category in category_list %}
                {% if category.novel_set.all %}
                <li>
                    <strong style="float: left;"><a href="{{ category.get_category_url }}" style="color: #333333;text-decoration: none">{{ category }}:</a></strong>
                    {% for novel in category.novel_set.all %}<span class="text-center"><a href="{{ novel.get_novel_url }}">{{ novel }}</a></span>{% endfor %}
                    <strong style="float: right"><a href="{{ category.get_category_url }}" style="color: #333333;text-decoration: none">更多>></a></strong>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
    <div class="social">
    </div>
    <div class="index-page">
        <h2 class="category-hot text-center">{{ index_book.name }}<small>({{ index_book.author }})</small></h2>
        <div class="chapterlist row">
            {% for c in chapter %}
                <div class="col-md-4 chapter col-sm-4 limit-word">
                    <a href="{{ c.get_chapter_url }}" title="{{ c.name }}">{{ c.name }}</a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block youlian %}
    <h4>友情链接:</h4>
    <p class="youlian">
        {% for link in link_list %}
            <a href="{{ link.url|safe }}">{{ link.name }}</a>
        {% endfor %}
    </p>
{% endblock %}